import type { Metadata } from 'next';
import Header from '@_component/Header';

import './_styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="wrap">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
